apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
spec:
  selector:
    matchLabels:
      app: train-schedule
  replicas: 2
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: mikeletux/train-schedule:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service 
metadata:
  name: train-schedule-svc
  labels:
    app: train-schedule-app
spec:
  selector:
    app: train-schedule
  type: NodePort
  ports:
  - nodePort: 8080
    port: 8080
    targetPort: 8080